import { Product } from '../types';

export const FALLBACK_IMAGE = 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&q=80&w=800';

export const PRODUCTS: Product[] = [
  {
    id: 'dark-velvet-ganache',
    name: 'Dark Velvet Ganache',
    category: 'Signature Cakes',
    price: 38.00,
    description: 'Triple-layer Valrhona dark chocolate cake layered with silky chocolate ganache, fresh raspberries, and edible 24k gold leaf accents.',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&q=80&w=800',
    bannerImage: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&q=80&w=1200',
    tag: 'Indulgent',
    badge: 'Chef Choice',
    isChefSelection: true,
    chefTag: 'Indulgent',
    chefActionText: 'Pre-order now',
    subtitle: 'Signature Chef Selection',
    features: ['Triple Layer', '24k Gold Leaf', 'Valrhona Chocolate'],
    ingredients: 'Contains dairy, eggs, gluten, and dark chocolate. Prepared in an environment that processes nuts.',
    personalization: 'Custom gold ribbon box and personalized plaque included upon request.',
    pairsWithIds: ['vanilla-latte', 'espresso-hazelnut'],
    allergens: ['Dairy', 'Eggs', 'Gluten']
  },
  {
    id: 'lavender-lemon-dream',
    name: 'Lavender Lemon Dream',
    category: 'Signature Cakes',
    price: 34.00,
    description: 'Organic Meyer lemon chiffon sponge layered with French lavender mascarpone cream and finished with dried edible flower petals.',
    image: 'https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?auto=format&fit=crop&q=80&w=800',
    bannerImage: 'https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?auto=format&fit=crop&q=80&w=1200',
    tag: 'Seasonal',
    badge: 'New Arrival',
    isChefSelection: true,
    chefTag: 'Seasonal',
    chefActionText: 'Explore collection',
    subtitle: 'Seasonal Botanical Series',
    features: ['Meyer Lemon', 'Organic Lavender', 'Mascarpone Cream'],
    ingredients: 'Contains wheat flour, fresh eggs, organic lemon juice, lavender flowers, and cream cheese.',
    personalization: 'Includes a keepsake botanical message card.',
    pairsWithIds: ['vanilla-latte', 'rose-petal-macarons'],
    allergens: ['Dairy', 'Eggs', 'Gluten']
  },
  {
    id: 'strawberry-artisan',
    name: 'Strawberry Artisan',
    category: 'Signature Cakes',
    price: 32.00,
    description: 'Fluffy Japanese sponge cake with layers of fresh organic strawberries and light Madagascar vanilla bean diplomat cream.',
    image: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&q=80&w=800',
    bannerImage: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&q=80&w=1200',
    tag: 'Classic',
    isChefSelection: true,
    chefTag: 'Classic',
    chefActionText: 'Customize order',
    subtitle: 'Classic Bakery Favorite',
    features: ['Fresh Strawberries', 'Vanilla Bean', 'Light & Fluffy'],
    ingredients: 'Contains organic strawberries, heavy cream, cake flour, sugar, and farm eggs.',
    personalization: 'Add a customized chocolate birthday message disc.',
    pairsWithIds: ['vanilla-latte', 'lemon-meringue-tart'],
    allergens: ['Dairy', 'Eggs', 'Gluten']
  },
  {
    id: 'signature-macaron-box',
    name: 'Signature Macaron Box',
    category: 'Macarons',
    price: 24.00,
    description: 'A curated selection of 6 handcrafted macarons featuring seasonal floral and nut ganaches. Each shell is naturally aged for 24 hours to achieve the perfect balance of a crisp exterior and a melt-in-your-mouth interior.',
    image: 'https://images.unsplash.com/photo-1569864358642-9d1684040f43?auto=format&fit=crop&q=80&w=800',
    bannerImage: 'https://images.unsplash.com/photo-1569864358642-9d1684040f43?auto=format&fit=crop&q=80&w=1200',
    badge: 'Best Seller',
    subtitle: 'Artisanal Pastry Series',
    features: ['Box of 6', 'Seasonal Flavors', 'Gift Ready'],
    ingredients: 'Contains almonds, eggs, and dairy. Best enjoyed within 3 days. Keep refrigerated for freshness.',
    personalization: 'Complimentary gift note included with every signature box purchase.',
    pairsWithIds: ['vanilla-latte', 'raspberry-pistachio-tart'],
    allergens: ['Almonds', 'Eggs', 'Dairy']
  },
  {
    id: 'honey-butter-croissant',
    name: 'Honey Butter Croissant',
    category: 'Croissants',
    price: 4.50,
    description: 'Infused with wildflower honey and churned artisan butter for a delicate, sweet finish.',
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&q=80&w=800',
    bannerImage: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&q=80&w=1200',
    badge: 'New Arrival',
    subtitle: 'French viennoiserie',
    features: ['Butter Flaked', 'Wildflower Honey', 'Baked Daily'],
    ingredients: 'French butter T84, organic wheat flour, wildflower honey, active yeast, pinch of sea salt.',
    personalization: 'Warm up instructions provided on packaging.',
    pairsWithIds: ['vanilla-latte'],
    allergens: ['Dairy', 'Gluten']
  },
  {
    id: 'midnight-cocoa-torte',
    name: 'Midnight Cocoa Torte',
    category: 'Signature Cakes',
    price: 8.50,
    description: '70% Belgian chocolate flourless torte with a fresh raspberry coulis center.',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&q=80&w=800',
    bannerImage: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&q=80&w=1200',
    subtitle: 'Flourless Chocolate Series',
    features: ['Flourless', '70% Belgian Cocoa', 'Raspberry Coulis'],
    ingredients: 'Dark chocolate 70%, organic eggs, butter, cocoa powder, fresh raspberries.',
    personalization: 'Served with extra raspberry coulis on the side.',
    pairsWithIds: ['vanilla-latte', 'espresso-hazelnut'],
    allergens: ['Dairy', 'Eggs']
  },
  {
    id: 'vanilla-bean-sparkle',
    name: 'Vanilla Bean Sparkle',
    category: 'Cupcakes',
    price: 4.50,
    description: 'Soft vanilla sponge filled with custard cream and topped with silky whipped buttercream and pearl sprinkles.',
    image: 'https://images.unsplash.com/photo-1519869325930-281384150729?auto=format&fit=crop&q=80&w=800',
    subtitle: 'Classic Bakery Cupcake',
    features: ['Madagascar Vanilla', 'Custom Sprinkles', 'Fresh Baked'],
    ingredients: 'Madagascar vanilla beans, organic flour, butter, sugar, pasteurized egg whites.',
    pairsWithIds: ['vanilla-latte'],
    allergens: ['Dairy', 'Eggs', 'Gluten']
  },
  {
    id: 'midnight-sea-salt',
    name: 'Midnight Sea Salt',
    category: 'Cookies',
    price: 3.25,
    description: 'Thick dark chocolate chunk cookie sprinkled with coarse Maldon sea salt flakes.',
    image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&q=80&w=800',
    subtitle: 'Decadent Chocolate Cookie',
    features: ['Maldon Sea Salt', 'Semi-Sweet Chunks', 'Chewy Center'],
    ingredients: 'Dark chocolate chunks, brown sugar, butter, flour, Maldon sea salt flakes.',
    pairsWithIds: ['vanilla-latte'],
    allergens: ['Dairy', 'Eggs', 'Gluten']
  },
  {
    id: 'pistachio-rose',
    name: 'Pistachio Rose',
    category: 'Macarons',
    price: 2.75,
    description: 'Artisanal macaroon filled with roasted Sicilian pistachio cream and subtle rose water essence.',
    image: 'https://images.unsplash.com/photo-1569864358642-9d1684040f43?auto=format&fit=crop&q=80&w=800',
    subtitle: 'Artisanal Macaroon',
    features: ['Sicilian Pistachio', 'Rose Water', 'Gluten Friendly'],
    ingredients: 'Almond flour, egg whites, sugar, pistachio paste, rose water.',
    pairsWithIds: ['vanilla-latte'],
    allergens: ['Almonds', 'Pistachio', 'Eggs']
  },
  {
    id: 'espresso-hazelnut',
    name: 'Espresso Hazelnut',
    category: 'Brownies',
    price: 4.00,
    description: 'Fudge brownie square infused with rich espresso coffee, drizzled with caramel and roasted hazelnut pieces.',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&q=80&w=800',
    subtitle: 'Fudge Brownie',
    features: ['Espresso Infused', 'Roasted Hazelnuts', 'Caramel Drizzle'],
    ingredients: 'Belgian cocoa, espresso beans, toasted hazelnuts, butter, organic sugar.',
    pairsWithIds: ['vanilla-latte'],
    allergens: ['Hazelnuts', 'Dairy', 'Eggs', 'Gluten']
  },
  {
    id: 'lemon-meringue-tart',
    name: 'Lemon Meringue Tart',
    category: 'Tarts',
    price: 7.50,
    description: 'Crisp buttery pastry shell filled with tangy Meyer lemon curd, crowned with fluffy toasted meringue peaks.',
    image: 'https://images.unsplash.com/photo-1519869325930-281384150729?auto=format&fit=crop&q=80&w=800',
    subtitle: 'French Patisserie',
    features: ['Meyer Lemon', 'Toasted Meringue', 'Buttery Shell'],
    ingredients: 'Butter crust, Meyer lemon curd, egg white meringue, powdered sugar.',
    pairsWithIds: ['vanilla-latte'],
    allergens: ['Dairy', 'Eggs', 'Gluten']
  },
  {
    id: 'honey-wheat-sourdough',
    name: 'Honey Wheat Sourdough',
    category: 'Pastries',
    price: 12.00,
    description: 'Naturally leavened 36-hour sourdough loaf made with whole stoneground wheat and wildflower honey.',
    image: 'https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?auto=format&fit=crop&q=80&w=800',
    subtitle: 'Daily Small Batch',
    features: ['36-Hour Fermentation', 'Stoneground Wheat', 'Wildflower Honey'],
    ingredients: 'Filtered water, organic wheat flour, sourdough starter, wildflower honey, sea salt.',
    pairsWithIds: ['vanilla-latte'],
    allergens: ['Gluten']
  },
  {
    id: 'pistachio-eclair',
    name: 'Pistachio Eclair',
    category: 'Pastries',
    price: 6.50,
    description: 'Choux pastry stick filled with silky pistachio creme patissiere, glazed with pistachio fondant and crushed nuts.',
    image: 'https://images.unsplash.com/photo-1612203985729-70726954388c?auto=format&fit=crop&q=80&w=800',
    subtitle: 'Artisanal Series',
    features: ['Pistachio Creme', 'Crisp Choux', 'Hand Glazed'],
    ingredients: 'Egg choux dough, milk, pistachio cream, butter, crushed roasted pistachios.',
    pairsWithIds: ['vanilla-latte'],
    allergens: ['Pistachio', 'Dairy', 'Eggs', 'Gluten']
  },
  {
    id: 'raspberry-pistachio-tart',
    name: 'Raspberry Pistachio Tart',
    category: 'Tarts',
    price: 8.50,
    description: 'Sweet tart shell layered with pistachio almond frangipane and topped with vibrant fresh raspberries.',
    image: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&q=80&w=800',
    subtitle: 'Signature Artisanal Series',
    features: ['Fresh Raspberries', 'Frangipane', 'Artisan Crust'],
    ingredients: 'Fresh organic raspberries, almond meal, pistachio paste, eggs, butter crust.',
    pairsWithIds: ['vanilla-latte'],
    allergens: ['Almonds', 'Pistachio', 'Dairy', 'Eggs', 'Gluten']
  },
  {
    id: 'rose-petal-macarons',
    name: 'Rose Petal Macarons',
    category: 'Macarons',
    price: 14.00,
    description: 'Set of 4 delicate blush pink macarons filled with Damask rose blossom ganache.',
    image: 'https://images.unsplash.com/photo-1569864358642-9d1684040f43?auto=format&fit=crop&q=80&w=800',
    subtitle: 'Box of 4',
    features: ['Box of 4', 'Rose Essence', 'White Chocolate'],
    ingredients: 'Almond flour, egg whites, white chocolate, organic rose water, edible glitter.',
    pairsWithIds: ['vanilla-latte'],
    allergens: ['Almonds', 'Eggs', 'Dairy']
  },
  {
    id: 'vanilla-latte',
    name: 'Vanilla Latte',
    category: 'Pastries',
    price: 4.50,
    description: 'Rich double espresso paired with steamed oat or whole milk and real Madagascar vanilla bean syrup.',
    image: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=800',
    subtitle: 'Handcrafted Coffee',
    features: ['Double Shot', 'Madagascar Vanilla', 'Microfoam Milk'],
    ingredients: 'Specialty espresso beans, milk of choice, house vanilla bean syrup.',
    pairsWithIds: ['signature-macaron-box', 'dark-velvet-ganache'],
    allergens: ['Dairy (optional Oat)']
  },
  {
    id: 'caramel-brownie',
    name: 'Caramel Brownie',
    category: 'Brownies',
    price: 5.00,
    description: 'Ultra-chewy chocolate brownie marbled with house-made salted caramel sauce.',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&q=80&w=800',
    subtitle: 'Gourmet Brownie',
    features: ['Salted Caramel', 'Gooey Center', 'Dark Chocolate'],
    ingredients: 'Butter, sugar, cocoa, flour, heavy cream salted caramel swirl.',
    pairsWithIds: ['vanilla-latte'],
    allergens: ['Dairy', 'Eggs', 'Gluten']
  }
];
